book:
  service:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak

server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/master
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: biZjoGFkmCNOkF29PM1E6UdzHA6bP2Hy
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

logging:
  level:
    web: debug