server:
  port: 8888
spring:
  application:
    name: book-config-server
  cloud:
    config:
      server:
        git:
          uri:
          clone-on-start: true
          default-label: master
          search-paths:
            - '{application}/{profile}'