server:
  port: 8083
books:
  services:
    catalogue:
      uri: lb://book-catalogue-service
    feedback:
      uri: lb://book-feedback-service
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/book-app
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: Q7tsHJmWs4PtvFAtoCEydYAbx1IHkREk
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app
            client-secret: Q7tsHJmWs4PtvFAtoCEydYAbx1IHkREk
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: Q7tsHJmWs4PtvFAtoCEydYAbx1IHkREk
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: book-customer-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
